language: node_js  #设置语言

node_js: stable  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo generate  #生成

after_script:
  - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config user.name "littlevoice-g-string"  #修改name
  - git config user.email "joreymiho@hotmail.com"  #修改email
  - git add .
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置环境变量的名称

branches:
  only:
    - master  #只监测master分支，master是我的分支的名称，可根据自己情况设置
local-dir: public
env:
 global:
   - GH_REF: github.com/littlevoice-g-string/Jorey-s-Blog #设置GH_REF，注意更改yourname

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - joreymiho@hotmail.com
  on_success: change
  on_failure: always
